### ISSUE TITLE
Using old voidlinux.eu domain

### ISSUE THREAD

**Issue by Noah-Huppert** [chneukirchen/hrmpf#8]
The XBPS tool is using the deprecated voidlinux.eu domain. Which no longer responds to requests. Making all package installations fail.

**Comment by chneukirchen** [comment]
I'll provide new images when I get around building ones.  For the meantime, hack `/usr/share/xbps.d/00-repository-main.conf`.

**Comment by chneukirchen** [comment]
Fixed in v20190116

**Comment by Haagen-Dazs** [comment]
New [Mirror Default](https://voidlinux.org/news/2022/05/default-mirror.html).
