### ISSUE TITLE
musl

### ISSUE THREAD

**Issue by ndowens** [chneukirchen/hrmpf#9]
Was wondering if you could make a musl version with zfs included?

**Comment by chneukirchen** [comment]
What's the benefit?

**Comment by chneukirchen** [comment]
You can just hack mkhrmpf.sh to create a musl version, not interested in maintaining one.

**Comment by dm17** [comment]
> I guess choice? Some people use musl, so this might benefit them. I tried to make my own with mklive but ran into issues and I used your iso before to install Void on ZFS

Note that you can still use hrmpf to install a musl system.
